// <auto-generated />
namespace GradeRegZTP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tmp444 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tmp444));
        
        string IMigrationMetadata.Id
        {
            get { return "201901131819397_tmp444"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
